import { ThemeProvider } from "@/components/theme-provider"
import "./globals.css"
import { Inter } from 'next/font/google'
import { LanguageProvider } from "@/hooks/use-language";
import AppLayout from "./components/AppLayout";
import { Toaster } from "sonner";

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

function App() {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <LanguageProvider>
            <AppLayout />
          </LanguageProvider>
        </ThemeProvider>
        <Toaster position="top-center" />
      </body>
    </html>
  )
}

export default App;
