// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});

/**
 * Runtime helper to check whether VITE supabase env vars are present.
 * Use this in UI flows to provide a clearer error message when the app
 * wasn't configured with the correct Supabase project keys.
 */
export function isSupabaseConfigured(): boolean {
  if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
    // Helpful console output for debugging (do not leak secrets)
    console.error('[supabase] missing VITE_SUPABASE_URL or VITE_SUPABASE_PUBLISHABLE_KEY');
    return false;
  }
  return true;
}